# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{subscribed_to}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["whtt-eric"]
  s.date = %q{2011-05-18}
  s.description = %q{Abstract layer for managing mailing list subscriptions}
  s.email = %q{eric@wehaventthetime.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/generators/subscribed_to/USAGE",
    "lib/generators/subscribed_to/install_generator.rb",
    "lib/generators/subscribed_to/templates/migration.rb",
    "lib/generators/subscribed_to/templates/subscribed_to.rb",
    "lib/subscribed_to.rb",
    "lib/subscribed_to/mail_chimp.rb",
    "lib/subscribed_to/mail_chimp/config.rb",
    "lib/subscribed_to/version.rb",
    "spec/app/models/user.rb",
    "spec/database.yml.example",
    "spec/factories/users.rb",
    "spec/generators/install_generator_spec.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb",
    "spec/subscribed_to/mail_chimp/config_spec.rb",
    "spec/subscribed_to/mail_chimp_spec.rb",
    "spec/subscribed_to_spec.rb"
  ]
  s.homepage = %q{http://github.com/whtt-eric/subscribed_to}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Abstract layer for managing mailing list subscriptions}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<hominid>, [">= 3.0.2"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<factory_girl_rails>, ["= 1.0.1"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.12"])
      s.add_development_dependency(%q<rspec-rails>, ["= 2.5.0"])
      s.add_development_dependency(%q<generator_spec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0.4.0"])
      s.add_development_dependency(%q<hanna>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<hominid>, [">= 3.0.2"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<factory_girl_rails>, ["= 1.0.1"])
      s.add_dependency(%q<mocha>, ["= 0.9.12"])
      s.add_dependency(%q<rspec-rails>, ["= 2.5.0"])
      s.add_dependency(%q<generator_spec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<simplecov>, [">= 0.4.0"])
      s.add_dependency(%q<hanna>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<hominid>, [">= 3.0.2"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<factory_girl_rails>, ["= 1.0.1"])
    s.add_dependency(%q<mocha>, ["= 0.9.12"])
    s.add_dependency(%q<rspec-rails>, ["= 2.5.0"])
    s.add_dependency(%q<generator_spec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<simplecov>, [">= 0.4.0"])
    s.add_dependency(%q<hanna>, [">= 0"])
  end
end

